apiVersion: zeabur.com/v1
kind: ZeaburService
metadata:
  name: asahihuuhu
spec:
  template: DOCKERFILE
  ports:
    - protocol: HTTP
      port: 3000
  env:
    - key: NODE_ENV
      value: production
    - key: NEXT_TELEMETRY_DISABLED
      value: "1"
